import type { Metadata } from "next";
import "@/app/globals.css";
import "@/app/globals.css";
import Navbar from "@/app/components/organisms/Navbar";
import Script from "next/script";

const GA_MEASUREMENT_ID = process.env.NEXT_PUBLIC_GA_ID;

// export const metadata: Metadata = {
//   title: "MAB SOTHEA - MLOps Engineer",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  title: "MAB SOTHEA - MLOps Engineer | Data Analyst",
  description: "Portfolio of MAB SOTHEA - Expertise in MLOps, Data Analytics, Visualization, and AI Solutions.",
  keywords: [
    "MAB SOTHEA",
    "MLOps Engineer",
    "Data Analyst",
    "Data Visualization",
    "Portfolio",
    "AI Solutions",
    "Next.js",
    "Machine Learning",
    "Data Science",
    "Cloud Engineer"
  ],
  authors: [{ name: "MAB SOTHEA", url: "https://portfolio-three-iota-15.vercel.app" }],
  creator: "MAB SOTHEA",
  publisher: "MAB SOTHEA",
  openGraph: {
    title: "MAB SOTHEA - MLOps Engineer | Data Analyst",
    description: "Explore the professional portfolio of MAB SOTHEA: MLOps, data analysis, AI engineering, and visualization projects.",
    url: "https://portfolio-three-iota-15.vercel.app",
    siteName: "MAB SOTHEA Portfolio",
    images: [
      {
        url: "https://portfolio-three-iota-15.vercel.app/og-image.jpg", // <-- make sure this image exists inside /public
        width: 1200,
        height: 630,
        alt: "MAB SOTHEA Portfolio Open Graph Image",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "MAB SOTHEA - MLOps Engineer | Data Analyst",
    description: "Discover MAB SOTHEA's portfolio showcasing skills in data analytics, MLOps, and AI solutions.",
    images: ["https://portfolio-three-iota-15.vercel.app/og-image.jpg"], // same as OpenGraph image
    creator: "@yourTwitterHandle", // <-- update this if you have a Twitter!
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  metadataBase: new URL("https://portfolio-three-iota-15.vercel.app"),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        {GA_MEASUREMENT_ID && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', '${GA_MEASUREMENT_ID}');
              `}
            </Script>
          </>
        )}

        <Navbar />
        <div className="flex w-full">{children}</div>
      </body>
    </html>
  );
}