import type { Metadata } from "next";
import "@/app/globals.css";
import "./globals.css";
import Navbar from "./components/organisms/Navbar";

export const metadata: Metadata = {
  title: "Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Navbar />
        <div className="flex w-full">{children}</div>
      </body>
    </html>
  );
}