name: Build and Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build the project
        run: bun run build

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        # with:
          # vercel-token: ${{ secrets.VERCEL_TOKEN }}
          # vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          # vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}